services:
  redis:
    container_name: redis-7.0.11-bullseye
    image: redis:7.0.11-bullseye
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data:/data
    restart: always
    ports:
      - "6379:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf --appendonly yes