services:
  pgsql:
    container_name: pgsql-15
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 1123581321345589
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    ports:
      - "5432:5432"
    privileged: true
