networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.179.0.0/24

services:
  redis-sentinel1:
    container_name: redis-7.0.11-bullseye-sentinel1
    image: redis:7.0.11-bullseye
    volumes:
      - ./sentinel/redis-sentinel1/conf/sentinel.conf:/etc/redis/sentinel.conf
      - ./sentinel/redis-sentinel1/data:/data
    restart: always
    ports:
      - "26479:26379"
    privileged: true
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      default:
        ipv4_address: 172.179.0.201
  
  redis-sentinel2:
    container_name: redis-7.0.11-bullseye-sentinel2
    image: redis:7.0.11-bullseye
    volumes:
      - ./sentinel/redis-sentinel2/conf/sentinel.conf:/etc/redis/sentinel.conf
      - ./sentinel/redis-sentinel2/data:/data
    restart: always
    ports:
      - "26579:26379"
    privileged: true
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      default:
        ipv4_address: 172.179.0.202
  
  redis-sentinel3:
    container_name: redis-7.0.11-bullseye-sentinel3
    image: redis:7.0.11-bullseye
    volumes:
      - ./sentinel/redis-sentinel3/conf/sentinel.conf:/etc/redis/sentinel.conf
      - ./sentinel/redis-sentinel3/data:/data
    restart: always
    ports:
      - "26679:26379"
    privileged: true
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      default:
        ipv4_address: 172.179.0.203

  redis-master:
    container_name: redis-7.0.11-bullseye-master
    image: redis:7.0.11-bullseye
    volumes:
      - ./server/redis-master/conf/redis.conf:/etc/redis/redis.conf
      - ./server/redis-master/data:/data
    restart: always
    ports:
      - "6379:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.100
  
  redis-slave1:
    container_name: redis-7.0.11-bullseye-slave1
    image: redis:7.0.11-bullseye
    volumes:
      - ./server/redis-slave1/conf/redis.conf:/etc/redis/redis.conf
      - ./server/redis-slave1/data:/data
    restart: always
    ports:
      - "6479:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.101

  redis-slave2:
    container_name: redis-7.0.11-bullseye-slave2
    image: redis:7.0.11-bullseye
    volumes:
      - ./server/redis-slave2/conf/redis.conf:/etc/redis/redis.conf
      - ./server/redis-slave2/data:/data
    restart: always
    ports:
      - "6579:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.102