networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.179.0.0/24

services:
  redis-cluster:
    container_name: redis-7.0.11-bullseye-prototype
    image: redis:7.0.11-bullseye
    command: redis-cli --cluster create 172.179.0.101:6379 172.179.0.102:6380 172.179.0.103:6381 172.179.0.104:6382 172.179.0.105:6383 172.179.0.106:6384 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

  redis-node1:
    container_name: redis-7.0.11-bullseye-node1
    image: redis:7.0.11-bullseye
    volumes:
      - ./redis-node1/conf/redis.conf:/etc/redis/redis.conf
      - ./redis-node1/data:/data
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "16379:16379"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.101

  redis-node2:
    container_name: redis-7.0.11-bullseye-node2
    image: redis:7.0.11-bullseye
    volumes:
      - ./redis-node2/conf/redis.conf:/etc/redis/redis.conf
      - ./redis-node2/data:/data
    restart: unless-stopped
    ports:
      - "6380:6380"
      - "16380:16380"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.102

  redis-node3:
    container_name: redis-7.0.11-bullseye-node3
    image: redis:7.0.11-bullseye
    volumes:
      - ./redis-node3/conf/redis.conf:/etc/redis/redis.conf
      - ./redis-node3/data:/data
    restart: unless-stopped
    ports:
      - "6381:6381"
      - "16381:16381"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.103

  redis-node4:
    container_name: redis-7.0.11-bullseye-node4
    image: redis:7.0.11-bullseye
    volumes:
      - ./redis-node4/conf/redis.conf:/etc/redis/redis.conf
      - ./redis-node4/data:/data
    restart: unless-stopped
    ports:
      - "6382:6382"
      - "16382:16382"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.104
  
  redis-node5:
    container_name: redis-7.0.11-bullseye-node5
    image: redis:7.0.11-bullseye
    volumes:
      - ./redis-node5/conf/redis.conf:/etc/redis/redis.conf
      - ./redis-node5/data:/data
    restart: unless-stopped
    ports:
      - "6383:6383"
      - "16383:16383"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.105

  redis-node6:
    container_name: redis-7.0.11-bullseye-node6
    image: redis:7.0.11-bullseye
    volumes:
      - ./redis-node6/conf/redis.conf:/etc/redis/redis.conf
      - ./redis-node6/data:/data
    restart: unless-stopped
    ports:
      - "6384:6384"
      - "16384:16384"
    privileged: true
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.179.0.106